# Jour 10 - 24 Juillet 2026 : Manipulation de Données avec Pandas

**Pandas** est l'outil incontournable pour analyser des données tabulaires (comme des fichiers Excel ou CSV). Il utilise deux structures principales : les **Series** (1 colonne) et les **DataFrames** (un tableau avec des lignes et des colonnes).

In [3]:
import pandas as pd

# Création d'un DataFrame (tableau) à partir d'un dictionnaire
donnees = {
    'Nom': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Ville': ['Paris', 'Lyon', 'Marseille']
}

df = pd.DataFrame(donnees)
df

       Nom  Age      Ville
0    Alice   25      Paris
1      Bob   30       Lyon
2  Charlie   35  Marseille

## Sélection de données
On peut sélectionner une seule colonne avec `df['NomColonne']` ou plusieurs avec une liste de colonnes.

In [4]:
# Sélectionner seulement la colonne Age
print(df['Age'])

# Filtrer les personnes de plus de 28 ans
plus_de_28 = df[df['Age'] > 28]
plus_de_28

0    25
1    30
2    35
Name: Age, dtype: int64

       Nom  Age      Ville
1      Bob   30       Lyon
2  Charlie   35  Marseille

---
## 🏆 Défi du Jour 10

1. Créez un DataFrame `df_employes` contenant 3 employés avec les colonnes : `Nom`, `Salaire`, et `Service`.
2. Affichez uniquement la colonne `Salaire`.
3. Filtrez et affichez uniquement les employés qui gagnent plus de 2500 (inventez les valeurs pour que le filtre fonctionne).

In [6]:
# Écrivez votre code pour le défi ici
employes = {
    'Nom' : ['Alice', 'Bob', 'Charlie', 'Abdou'],
    'Salaire' : [2500, 3000000, 3500000, 1500],
    'Service' : ['Assistance', 'Conseiller', 'Informaticien', 'Admin Systeme']
}
df_employes = pd.DataFrame(employes)
print(df_employes['Salaire'])
aff_salaire = df_employes[df_employes['Salaire'] > 2500]
aff_salaire

0       2500
1    3000000
2    3500000
3       1500
Name: Salaire, dtype: int64

       Nom  Salaire        Service
1      Bob  3000000     Conseiller
2  Charlie  3500000  Informaticien